name: open_saves
description: gRPC generated client for Open Saves - an open-source, purpose-built single interface 
  for multiple storage backends on Google Cloud.
version: 0.2.0-beta2
homepage: https://markvideon.dev

environment:
  sdk: '>=2.18.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  fixnum: ^1.0.1
  grpc: ^3.1.0
  protobuf: ^2.1.0
